### ISSUE TITLE
Sporadic test failure in plugin and examples

### ISSUE THREAD

**Issue by durban** [durban/seals#50]
The `sbt-test/seals-plugin/example` test can (non-deterministically) fail. The problem is probably the same as #31.

**Comment by durban** [comment]
Also happens in `examples/lib/server/src/test/scala/com/example/lib/ServerSpec.scala`:

```
[info] ServerSpec:
[info] Server
[info] - should respond to requests *** FAILED ***
[info]   java.net.ConnectException: Connection refused
[info]   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
[info]   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
[info]   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
[info]   at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
[info]   at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
[info]   at java.lang.Thread.run(Thread.java:745)
[info]   at sun.misc.InnocuousThread.run(InnocuousThread.java:74)
[info]   ...
```
